### ISSUE TITLE
Unstable estimates at low levels of baseline proportion

### ISSUE THREAD

**Issue by Chris-Larkin** [heliosdrm/pwr#12]
Hello,

I'm getting some unstable estimates of the minimum detectable effect size when I set the baseline proportion at a very low level. For a binomial distribution we would expect a baseline proportion of 0.01 to produce the same estimate as 0.99. However, when I run the below code, changing the baseline proportion between the two I get quite different estimates.

We would also expect, holding all else constant and increasing the N, that the MDES goes down. However, in the below case if i increase the N up to 1,000 the MDES goes up. 

```
## Backing out minimum detectable effect size ##

library(pwr)

n <- 200
arms <- 2
baselineProportion <- 0.01

nPerArm <- n/arms 
test <- pwr.2p.test(n=nPerArm, h=, sig.level = .05, power = 0.8, alternative = "two.sided")
treatmentProportion <- (sin(asin(sqrt(baselineProportion))-(test$h/2)))^2
baselineProportion - treatmentProportion
```

I figured this would be a sensible place to submit an issue but if you can't help and have suggestions of other places to post do let me know!

Cheers

**Comment by heliosdrm** [comment]
Hi, your problem is not related to the functions of the pwr package. The line:

``` R
test <- pwr.2p.test(n=nPerArm, h=, sig.level = .05, power = 0.8, alternative = "two.sided")
```

Produces the same result whatever baseline you set (in fact you don't use the baseline proportion in that call).

Another story is the "inversion" of the function `ES.h` that you have coded in the next line to calculate the treatment proportion. The code of `ES.h` is:

``` R
"ES.h" <-
function (p1, p2) 
{
    2 * asin(sqrt(p1)) - 2 * asin(sqrt(p2))
}
```

You have coded an inversion of that function where you get `p2` (the smaller proportion) from the effect size and `p1` (the greater proportion). But for the effect size that you have set and a baseline proportion equal to `0.01`, you should look for a _greater_ treatment proportion, i.e. obtain `p1` given the effect size and `p2`. Change the minus sign by plus, and you'll get it.

On the other hand, I have not been able to reproduce your problem of increasing MDES with greater sample sizes.
