### ISSUE TITLE
Is there a Python version of this package?

### ISSUE THREAD

**Issue by zigner-song** [heliosdrm/pwr#30]

**Comment by heliosdrm** [comment]
I don't use much Python for stats, but a popular package that includes some power analysis is [statsmodel](https://www.statsmodels.org/stable/index.html)

**Comment by ConorMcNamara** [comment]
Sorry to necro this but I reverse-engineered pwr into pyPWR. Note that I have not uploaded this to PyPI due to lack of time. 

https://github.com/ConorMcNamara/pyPWR

**Comment by heliosdrm** [comment]
@ConorMcNamara : That's a great job, thank you. However, there is an issue with the license. The R package was published by its original creator, Stephane Champely, under [GPL3, which is incompatible with the MIT license](https://www.tawesoft.co.uk/kb/article/mit-license-faq#can-i-use-mit-licensed-code-in-my-gpl-licensed-project) that you have chosen. Therefore, I'm afraid that you should change the MIT license by GPL3 or a compatible one, in order to respect the original license. I hope that's not a big trouble.

**Comment by ConorMcNamara** [comment]
@heliosdrm Just changed the license to be GPL3.
